Repository kemitix/thorp, pull requests merged in 2019-08, with the labels that each got.

#137 Refactor Copier.copyObject(AmazonS3.Client,Bucket,RemoteKey,MD5Hash,RemoteKey)
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigOption.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigValidationException.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigValidator.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigurationBuilder.scala
  config/src/main/scala/net/kemitix/thorp/config/ParseConfigFile.scala
  config/src/main/scala/net/kemitix/thorp/config/ParseConfigLines.scala
  config/src/main/scala/net/kemitix/thorp/config/SourceConfigLoader.scala
  config/src/test/scala/net/kemitix/thorp/config/ConfigOptionTest.scala
  config/src/test/scala/net/kemitix/thorp/config/ConfigQueryTest.scala
  config/src/test/scala/net/kemitix/thorp/config/ConfigurationBuilderTest.scala
  config/src/test/scala/net/kemitix/thorp/config/ParseConfigFileTest.scala
  config/src/test/scala/net/kemitix/thorp/config/ParseConfigLinesTest.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/CoreTypes.scala
  core/src/main/scala/net/kemitix/thorp/core/HashService.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/SimpleHashService.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/hasher/Hasher.scala
  core/src/main/scala/net/kemitix/thorp/core/hasher/MD5HashGenerator.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyHashService.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigLinesTest.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/hasher/MD5HashGeneratorTest.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Filter.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Monoid.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Sources.scala
  domain/src/test/scala/net/kemitix/thorp/domain/FiltersSuite.scala
  domain/src/test/scala/net/kemitix/thorp/domain/TemporaryFolder.scala
  filesystem/src/main/scala/net/kemitix/thorp/filesystem/FileSystem.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Copier.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3HashService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/hasher/ETagGenerator.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/hasher/S3Hasher.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/CopierTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/hasher/ETagGeneratorTest.scala
Labels: good first issue

#129 Refactor Uploader.upload(LocalFile,Bucket,Boolean,UploadEventListener,Int)
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyStorageService.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
Labels: good first issue

#128 Refactor UploadEventLogger.statusWithBar(String,Long=>String,Long,Long,Long)
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyStorageService.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventListener.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventLogger.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
Labels: good first issue

#141 Refactor ThorpArchive.logEvent(StorageQueueEvent)
  build.sbt
  console/src/main/scala/net/kemitix/thorp/console/Console.scala
  console/src/main/scala/net/kemitix/thorp/console/ConsoleOut.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
Labels: refactoring

#142 Refactor Program.updateArchive(ThorpArchive,Action,Int,Stream,Long)
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  core/src/main/scala/net/kemitix/thorp/core/EventQueue.scala
  core/src/main/scala/net/kemitix/thorp/core/SequencedAction.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
Labels: refactoring

#144 Update aws-java-sdk-s3 to 1.11.603
  build.sbt
Labels: dependencies

#145 Progress Bar only appears for first file
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventListener.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
Labels: bug

#146 Amazon falls back on it's own slow implementation when JABX not available (JDK9+)
  build.sbt
Labels: bug

#147 case classes shouldn't be OO objects
  build.sbt
  config/src/main/scala/net/kemitix/thorp/config/ConfigValidation.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigurationBuilder.scala
  config/src/main/scala/net/kemitix/thorp/config/ParseConfigFile.scala
  config/src/main/scala/net/kemitix/thorp/config/SourceConfigLoader.scala
  config/src/test/scala/net/kemitix/thorp/config/ParseConfigFileTest.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/Filters.scala
  core/src/main/scala/net/kemitix/thorp/core/KeyGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileValidator.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFiles.scala
  core/src/main/scala/net/kemitix/thorp/core/Remote.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/FiltersSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/KeyGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/S3MetaDataEnricherSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/hasher/MD5HashGeneratorTest.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Filter.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Logger.scala
  domain/src/main/scala/net/kemitix/thorp/domain/MD5Hash.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteKey.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Sources.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventListener.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventLogger.scala
  domain/src/test/scala/net/kemitix/thorp/domain/MD5HashTest.scala
  domain/src/test/scala/net/kemitix/thorp/domain/RemoteKeyTest.scala
  domain/src/test/scala/net/kemitix/thorp/domain/TemporaryFolder.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Copier.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/hasher/ETagGenerator.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/S3ObjectsByHashSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/hasher/ETagGeneratorTest.scala
Labels: refactoring

#143 Refactor ActionGenerator.genAction(S3MetaData,Stream,Bucket)
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/S3MetaDataEnricher.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyStorageService.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/MatchedMetadataEnricherSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  domain/src/main/scala/net/kemitix/thorp/domain/MatchedMetadata.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteObjects.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ListerTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
Labels: refactoring

#158 Update aws-java-sdk-s3 to 1.11.610
  build.sbt
Labels: dependencies

#165 Update scalamock to 4.4.0
  build.sbt
Labels: dependencies

#163 java.lang.StackOverflowError
  core/src/main/scala/net/kemitix/thorp/core/PlanExecutor.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanExecutorTest.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/Storage.scala
Labels: bug
