Repository kemitix/thorp, pull requests merged in 2019-06, with the labels that each got.

#32 Final case classes
  src/main/scala/net/kemitix/s3thorp/Action.scala
  src/main/scala/net/kemitix/s3thorp/Config.scala
  src/main/scala/net/kemitix/s3thorp/Counters.scala
  src/main/scala/net/kemitix/s3thorp/Exclude.scala
  src/main/scala/net/kemitix/s3thorp/Filter.scala
  src/main/scala/net/kemitix/s3thorp/LocalFile.scala
  src/main/scala/net/kemitix/s3thorp/S3Action.scala
  src/main/scala/net/kemitix/s3thorp/S3MetaData.scala
  src/main/scala/net/kemitix/s3thorp/SyncLogging.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/CancellableMultiPartUpload.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ObjectsData.scala
  src/test/scala/net/kemitix/s3thorp/UnitTest.scala
Labels: enhancement

#34 Inject Logger via CLI
  cli/src/main/scala/net/kemitix/s3thorp/cli/Logger.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Main.scala
  src/main/scala/net/kemitix/s3thorp/Action.scala
  src/main/scala/net/kemitix/s3thorp/ActionGenerator.scala
  src/main/scala/net/kemitix/s3thorp/ActionSubmitter.scala
  src/main/scala/net/kemitix/s3thorp/LocalFileStream.scala
  src/main/scala/net/kemitix/s3thorp/Logging.scala
  src/main/scala/net/kemitix/s3thorp/MD5HashGenerator.scala
  src/main/scala/net/kemitix/s3thorp/S3Action.scala
  src/main/scala/net/kemitix/s3thorp/S3MetaDataEnricher.scala
  src/main/scala/net/kemitix/s3thorp/Sync.scala
  src/main/scala/net/kemitix/s3thorp/SyncLogging.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3Client.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientCopier.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientDeleter.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientLogging.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientMultiPartTransferManager.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientMultiPartUploader.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientMultiPartUploaderLogging.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientObjectLister.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientPutObjectUploader.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/S3ClientUploader.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/ThorpS3Client.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/UploadEvent.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/UploadProgressListener.scala
  src/main/scala/net/kemitix/s3thorp/awssdk/UploadProgressLogging.scala
  src/test/scala/net/kemitix/s3thorp/ActionGeneratorSuite.scala
  src/test/scala/net/kemitix/s3thorp/DummyS3Client.scala
  src/test/scala/net/kemitix/s3thorp/LocalFileStreamSuite.scala
  src/test/scala/net/kemitix/s3thorp/MD5HashGeneratorTest.scala
  src/test/scala/net/kemitix/s3thorp/S3ActionSuite.scala
  src/test/scala/net/kemitix/s3thorp/S3MetaDataEnricherSuite.scala
  src/test/scala/net/kemitix/s3thorp/SyncSuite.scala
  src/test/scala/net/kemitix/s3thorp/awssdk/S3ClientMultiPartTransferManagerSuite.scala
  src/test/scala/net/kemitix/s3thorp/awssdk/S3ClientMultiPartUploaderSuite.scala
  src/test/scala/net/kemitix/s3thorp/awssdk/S3ClientSuite.scala
  src/test/scala/net/kemitix/s3thorp/awssdk/ThorpS3ClientSuite.scala
Labels: enhancement

#37 Improve Code Quality
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/QuoteStripper.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientMultiPartUploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientObjectLister.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientPutObjectUploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientUploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/ThorpS3Client.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientMultiPartTransferManagerSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientMultiPartUploaderSuite.scala
  core/src/main/scala/net.kemitix.s3thorp.core/ActionGenerator.scala
  core/src/main/scala/net.kemitix.s3thorp.core/QuoteStripper.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/Bucket.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/HashModified.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/KeyModified.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/LastModified.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/RemoteMetaData.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/S3ObjectsData.scala
Labels: enhancement

#41 Drop AWS SDK V2 client
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/JavaClientWrapper.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientBuilder.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientCopier.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientDeleter.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientMultiPartUploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientObjectLister.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientPutObjectUploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientTransferManager.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientTransferManagerLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ObjectsByHash.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ObjectsByKey.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/ThorpS3Client.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/MyAmazonS3.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/MyAmazonS3Client.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/MyS3CatsIOClient.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientMultiPartUploaderSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientTransferManagerSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ObjectsByHashSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/ThorpS3ClientSuite.scala
  build.sbt
  core/src/test/scala/net/kemitix/s3thorp/core/SyncSuite.scala
Labels: enhancement

#45 Fetch all hashes
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientObjectLister.scala
  core/src/main/scala/net.kemitix.s3thorp.core/MD5HashGenerator.scala
Labels: bug

#47 [core] MD5HashGenerator uses IO to return where there is file IO
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/MD5HashData.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientTransferManagerSuite.scala
  core/src/main/scala/net.kemitix.s3thorp.core/LocalFileStream.scala
  core/src/main/scala/net.kemitix.s3thorp.core/MD5HashGenerator.scala
  core/src/main/scala/net.kemitix.s3thorp.core/S3MetaDataEnricher.scala
  core/src/main/scala/net.kemitix.s3thorp.core/Sync.scala
  core/src/test/scala/net/kemitix/s3thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/s3thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/s3thorp/core/MD5HashData.scala
  core/src/test/scala/net/kemitix/s3thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/s3thorp/core/S3MetaDataEnricherSuite.scala
  core/src/test/scala/net/kemitix/s3thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/LocalFile.scala
Labels: enhancement

#48 Include and Exclude behave more like the AWS CLI
  cli/src/main/scala/net/kemitix/s3thorp/cli/ParseArgs.scala
  core/src/main/scala/net.kemitix.s3thorp.core/LocalFileStream.scala
  core/src/main/scala/net.kemitix.s3thorp.core/SyncLogging.scala
  core/src/test/scala/net/kemitix/s3thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/Config.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/Exclude.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/Filter.scala
  domain/src/test/scala/net/kemitix/s3thorp/domain/ExcludeSuite.scala
  domain/src/test/scala/net/kemitix/s3thorp/domain/FilterSuite.scala
  domain/src/test/scala/net/kemitix/s3thorp/domain/FiltersSuite.scala
Labels: enhancement

#44 Improve upload logging
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/S3Client.scala
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/UploadProgressListener.scala
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/UploadProgressLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/CancellableMultiPartUpload.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientCopier.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientDeleter.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientObjectLister.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientTransferManager.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientTransferManagerLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientUploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ObjectsByKey.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/ThorpS3Client.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/Uploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/UploaderLogging.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/ThorpS3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/UploaderSuite.scala
  build.sbt
  cli/src/main/resources/log4j.xml
  cli/src/main/scala/net/kemitix/s3thorp/cli/Logger.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Main.scala
  core/src/main/scala/net.kemitix.s3thorp.core/ActionSubmitter.scala
  core/src/main/scala/net.kemitix.s3thorp.core/LocalFileStream.scala
  core/src/main/scala/net.kemitix.s3thorp.core/MD5HashGenerator.scala
  core/src/main/scala/net.kemitix.s3thorp.core/Sync.scala
  core/src/main/scala/net.kemitix.s3thorp.core/SyncLogging.scala
  core/src/test/scala/net/kemitix/s3thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/s3thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/s3thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/MD5Hash.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/QuoteStripper.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/SizeTranslation.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/Terminal.scala
Labels: enhancement

#49 Handle when a file is not found after initial scan
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/Uploader.scala
  core/src/main/scala/net.kemitix.s3thorp.core/Counters.scala
  core/src/main/scala/net.kemitix.s3thorp.core/SyncLogging.scala
Labels: bug

#53 Update aws-java-sdk-s3 to 1.11.569
  build.sbt
Labels: dependencies

#56 Error when calculating MD5Hash for large files
  core/src/main/scala/net.kemitix.s3thorp.core/MD5HashGenerator.scala
  core/src/test/scala/net/kemitix/s3thorp/core/MD5HashGeneratorTest.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/SizeTranslation.scala
  domain/src/test/scala/net/kemitix/s3thorp/domain/SizeTranslationTest.scala
Labels: bug

#55 Enable running outside of sbt
  README.org
  bin/s3thorp
  build.sbt
  project/assembly.sbt
Labels: enhancement

#52 Improve purity by moving all IO out to the edge
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/S3Client.scala
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/UploadProgressListener.scala
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/UploadProgressLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientBuilder.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientCopier.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientDeleter.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientObjectLister.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/ThorpS3Client.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/Uploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/UploaderLogging.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ObjectsByHashSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/ThorpS3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/UploaderSuite.scala
  build.sbt
  cli/src/main/scala/net/kemitix/s3thorp/cli/Logger.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Main.scala
  core/src/main/scala/net.kemitix.s3thorp.core/ActionSubmitter.scala
  core/src/main/scala/net.kemitix.s3thorp.core/LocalFileStream.scala
  core/src/main/scala/net.kemitix.s3thorp.core/MD5HashGenerator.scala
  core/src/main/scala/net.kemitix.s3thorp.core/Sync.scala
  core/src/main/scala/net.kemitix.s3thorp.core/SyncLogging.scala
  core/src/test/scala/net/kemitix/s3thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/s3thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/s3thorp/core/SyncSuite.scala
Labels: enhancement

#57 Update aws-java-sdk-s3 to 1.11.570
  build.sbt
Labels: dependencies

#58 Tidy Main by extracting Program
  cli/src/main/scala/net/kemitix/s3thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/ParseArgs.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Program.scala
Labels: enhancement

#59 Simplify logging
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/S3Client.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientCopier.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientDeleter.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientLogging.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/S3ClientObjectLister.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/ThorpS3Client.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/Uploader.scala
  aws-lib/src/main/scala/net/kemitix/s3thorp/aws/lib/UploaderLogging.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/DummyLogger.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/S3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/ThorpS3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/s3thorp/aws/lib/UploaderSuite.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Logger.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/PrintLogger.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Program.scala
  core/src/main/scala/net.kemitix.s3thorp.core/ActionSubmitter.scala
  core/src/main/scala/net.kemitix.s3thorp.core/LocalFileStream.scala
  core/src/main/scala/net.kemitix.s3thorp.core/MD5HashGenerator.scala
  core/src/main/scala/net.kemitix.s3thorp.core/Sync.scala
  core/src/main/scala/net.kemitix.s3thorp.core/SyncLogging.scala
  core/src/test/scala/net/kemitix/s3thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/s3thorp/core/DummyLogger.scala
  core/src/test/scala/net/kemitix/s3thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/s3thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/s3thorp/core/S3MetaDataEnricherSuite.scala
  core/src/test/scala/net/kemitix/s3thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/Logger.scala
Labels: enhancement

#61 [core] Sync simplify the call to run
  cli/src/main/scala/net/kemitix/s3thorp/cli/Program.scala
  core/src/main/scala/net.kemitix.s3thorp.core/Sync.scala
  core/src/test/scala/net/kemitix/s3thorp/core/SyncSuite.scala
Labels: enhancement

#51 Better error message when source is not found
  build.sbt
  cli/src/main/scala/net/kemitix/s3thorp/cli/ParseArgs.scala
  cli/src/test/scala/net/kemitix/s3thorp/cli/ParseArgsTest.scala
Labels: enhancement

#60 Add a debug flag and make debug message hidden by default
  CHANGELOG.org
  README.org
  cli/src/main/scala/net/kemitix/s3thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/ParseArgs.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/PrintLogger.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Program.scala
  cli/src/test/scala/net/kemitix/s3thorp/cli/ParseArgsTest.scala
  core/src/main/scala/net.kemitix.s3thorp.core/LocalFileStream.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/Config.scala
Labels: enhancement

#64 Suppress "Transfer" event messages
  CHANGELOG.org
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/UploadProgressListener.scala
  aws-api/src/main/scala/net/kemitix/s3thorp/aws/api/UploadProgressLogging.scala
Labels: enhancement

#63 Remove unused verbosity command line option
  CHANGELOG.org
  README.org
  cli/src/main/scala/net/kemitix/s3thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/ParseArgs.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/PrintLogger.scala
  cli/src/main/scala/net/kemitix/s3thorp/cli/Program.scala
  domain/src/main/scala/net/kemitix/s3thorp/domain/Config.scala
Labels: enhancement

#66 Add a thorp-lib module between cli and aws-lib
  build.sbt
Labels: enhancement

#71 Add support for per directory configuration files
  aws-api/src/main/scala/net/kemitix/thorp/aws/api/S3Client.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/S3ClientBuilder.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/S3ClientCopier.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/S3ClientDeleter.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/S3ClientLogging.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/S3ClientObjectLister.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/ThorpS3Client.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/Uploader.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/UploaderLogging.scala
  aws-lib/src/test/scala/net/kemitix/thorp/aws/lib/DummyLogger.scala
  aws-lib/src/test/scala/net/kemitix/thorp/aws/lib/S3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/thorp/aws/lib/ThorpS3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/thorp/aws/lib/UploaderSuite.scala
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/ParseArgs.scala
  cli/src/main/scala/net/kemitix/thorp/cli/PrintLogger.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  cli/src/test/scala/net/kemitix/thorp/cli/ParseArgsTest.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionSubmitter.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOption.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigValidation.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigValidator.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigurationBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/MD5HashGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/ParseConfigFile.scala
  core/src/main/scala/net/kemitix/thorp/core/ParseConfigLines.scala
  core/src/main/scala/net/kemitix/thorp/core/Sync.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/test/resources/net/kemitix/thorp/core/empty-file
  core/src/test/resources/net/kemitix/thorp/core/invalid-config
  core/src/test/resources/net/kemitix/thorp/core/simple-config
  core/src/test/scala/net/kemitix/thorp/core/DummyLogger.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigFileTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigLinesTest.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Config.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Logger.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteKey.scala
Labels: enhancement

#73 Add support for global and user configuration files
  CHANGELOG.org
  README.org
  core/src/main/scala/net/kemitix/thorp/core/ConfigurationBuilder.scala
Labels: enhancement

#78 Smooth progress bar
  aws-api/src/main/scala/net/kemitix/thorp/aws/api/UploadProgressLogging.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/UploaderLogging.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Terminal.scala
  domain/src/test/scala/net/kemitix/thorp/domain/TerminalTest.scala
Labels: enhancement

#50 Is AWS SDK calculating MD5Hash again for a local file?
  CHANGELOG.org
  README.org
  aws-api/src/main/scala/net/kemitix/thorp/aws/api/S3Client.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/ThorpS3Client.scala
  aws-lib/src/main/scala/net/kemitix/thorp/aws/lib/Uploader.scala
  aws-lib/src/test/scala/net/kemitix/thorp/aws/lib/S3ClientSuite.scala
  aws-lib/src/test/scala/net/kemitix/thorp/aws/lib/UploaderSuite.scala
  cli/src/main/scala/net/kemitix/thorp/cli/ParseArgs.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionSubmitter.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOption.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigQuery.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigurationBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/MD5HashGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/Sync.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashData.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Config.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  domain/src/main/scala/net/kemitix/thorp/domain/MD5Hash.scala
Labels: enhancement

#74 Restructure sync to use a State with foldLeft around actions
  CHANGELOG.org
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/Sync.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/Synchronise.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashData.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Terminal.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventLogger.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ClientCopier.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ClientDeleter.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ClientLogging.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ClientObjectLister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/UploaderLogging.scala
Labels: enhancement

#84 Update scalamock to 4.3.0
  build.sbt
Labels: dependencies

#86 Update aws-java-sdk-s3 to 1.11.580
  build.sbt
Labels: dependencies

#81 Display simple error message when bucket is invalid
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/Synchronise.scala
  core/src/test/scala/net/kemitix/thorp/core/StorageQueueEventSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ClientObjectLister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageService.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/S3StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderSuite.scala
Labels: bug

#82 Use correct hash locally for comparing multi-part uploaded files
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/MD5HashGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/S3MetaDataEnricher.scala
  core/src/main/scala/net/kemitix/thorp/core/Synchronise.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyHashService.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashData.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/thorp/core/S3MetaDataEnricherSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/HexEncoder.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  domain/src/main/scala/net/kemitix/thorp/domain/MD5Hash.scala
  domain/src/test/scala/net/kemitix/thorp/domain/MD5HashData.scala
  domain/src/test/scala/net/kemitix/thorp/domain/MD5HashTest.scala
  project/plugins.sbt
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/HashService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ETagGenerator.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ClientObjectLister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3HashService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ETagGeneratorTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderSuite.scala
Labels: bug

#88 Check TransferManager is shutdown once transfer is complete.
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/StorageQueueEvent.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageServiceBuilder.scala
Labels: bug

#93 Stackoverflow on large collections of files
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
Labels: bug

#92 Release snapshots to sonatype from TravisCI
  .travis.yml
  build.sbt
  project/plugins.sbt
Labels: enhancement

#96 Include assembly jar in release
  .travis.yml
  build.sbt
Labels: enhancement

#97 Revert most of "publish fat-jar", keeping cli jar name
  .travis.yml
  build.sbt
Labels: bug

#98 Embed launch script in fat-jar
  build.sbt
Labels: enhancement

#99 Add a version command-line option
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/ParseArgs.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOption.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigQuery.scala
  project/plugins.sbt
Labels: enhancement
