Repository kemitix/thorp, pull requests merged in 2019-07, with the labels that each got.

#85 Add a batch mode that provides a simple log output
  CHANGELOG.org
  README.org
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/ParseArgs.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  cli/src/test/scala/net/kemitix/thorp/cli/ParseArgsTest.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOption.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOptions.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigQuery.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigurationBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/ParseConfigFile.scala
  core/src/main/scala/net/kemitix/thorp/core/ParseConfigLines.scala
  core/src/main/scala/net/kemitix/thorp/core/Synchronise.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigFileTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigLinesTest.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Config.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Copier.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Deleter.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageServiceBuilder.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderSuite.scala
Labels: enhancement

#102 Release to sonatype using correct profile name
  CHANGELOG.org
  build.sbt
Labels: bug

#101 Update jackson-databind to 2.9.9.1
  build.sbt
Labels: dependencies

#94 Display total size and progress for entire run
  CHANGELOG.org
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  cli/src/test/scala/net/kemitix/thorp/cli/ProgramTest.scala
  core/src/main/scala/net/kemitix/thorp/core/Action.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFiles.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncPlan.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/SyncTotals.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventListener.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventLogger.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ListerLogger.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageService.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderSuite.scala
Labels: enhancement

#104 Update aws-java-sdk-s3 to 1.11.587
  build.sbt
Labels: dependencies

#105 Update sbt-assembly to 0.14.10
  project/assembly.sbt
Labels: dependencies

#110 Not reading .thorp.conf file
  CHANGELOG.org
  core/src/main/scala/net/kemitix/thorp/core/ConfigurationBuilder.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigurationBuilderTest.scala
Labels: bug

#111 Not reading .thorp.conf file
  CHANGELOG.org
  core/src/main/scala/net/kemitix/thorp/core/ConfigQuery.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigurationBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/SourceConfigLoader.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigQueryTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigurationBuilderTest.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Config.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Sources.scala
Labels: bug

#113 Use Lenses
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/ParseArgs.scala
  core/src/main/scala/net/kemitix/thorp/core/Action.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOption.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOptions.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigurationBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/Counters.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFiles.scala
  core/src/main/scala/net/kemitix/thorp/core/SourceConfigLoader.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncPlan.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Bucket.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Config.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Filter.scala
  domain/src/main/scala/net/kemitix/thorp/domain/HashModified.scala
  domain/src/main/scala/net/kemitix/thorp/domain/KeyModified.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LastModified.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  domain/src/main/scala/net/kemitix/thorp/domain/MD5Hash.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteKey.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteMetaData.scala
  domain/src/main/scala/net/kemitix/thorp/domain/S3MetaData.scala
  domain/src/main/scala/net/kemitix/thorp/domain/S3ObjectsData.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Sources.scala
  domain/src/main/scala/net/kemitix/thorp/domain/StorageQueueEvent.scala
  domain/src/main/scala/net/kemitix/thorp/domain/SyncTotals.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEvent.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventListener.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderSuite.scala
Labels: enhancement

#103 Creates incorrect MD5 hash for some files
  core/src/test/resources/net/kemitix/thorp/core/File-6964
  domain/src/main/scala/net/kemitix/thorp/domain/HexEncoder.scala
  domain/src/test/scala/net/kemitix/thorp/domain/HexEncoderTest.scala
Labels: bug

#115 NullPointerException creating scaladoc
  CHANGELOG.org
  build.sbt
  core/src/main/scala/net/kemitix/thorp/core/Action.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOption.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOptions.scala
  core/src/main/scala/net/kemitix/thorp/core/Counters.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFiles.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncPlan.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Bucket.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Config.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Filter.scala
  domain/src/main/scala/net/kemitix/thorp/domain/HashModified.scala
  domain/src/main/scala/net/kemitix/thorp/domain/KeyModified.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LastModified.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  domain/src/main/scala/net/kemitix/thorp/domain/MD5Hash.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteKey.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteMetaData.scala
  domain/src/main/scala/net/kemitix/thorp/domain/S3MetaData.scala
  domain/src/main/scala/net/kemitix/thorp/domain/S3ObjectsData.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Sources.scala
  domain/src/main/scala/net/kemitix/thorp/domain/StorageQueueEvent.scala
  domain/src/main/scala/net/kemitix/thorp/domain/SyncTotals.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEvent.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventListener.scala
Labels: bug

#117 Replace cats-effect with zio
  CHANGELOG.org
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/ParseArgs.scala
  cli/src/main/scala/net/kemitix/thorp/cli/PrintLogger.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  cli/src/test/scala/net/kemitix/thorp/cli/ParseArgsTest.scala
  cli/src/test/scala/net/kemitix/thorp/cli/ProgramTest.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigOptions.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigValidation.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigValidationException.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigValidator.scala
  core/src/main/scala/net/kemitix/thorp/core/ConfigurationBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/MD5HashGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/ParseConfigFile.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/SimpleHashService.scala
  core/src/main/scala/net/kemitix/thorp/core/SourceConfigLoader.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigOptionTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigurationBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyHashService.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyLogger.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyStorageService.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigFileTest.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Logger.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/HashService.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Copier.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Deleter.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ETagGenerator.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ListerLogger.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3HashService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/DummyLogger.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ETagGeneratorTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/S3StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderSuite.scala
Labels: enhancement

#119 Improve logging consistency
  CHANGELOG.org
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  cli/src/test/scala/net/kemitix/thorp/cli/ProgramTest.scala
  console/src/main/scala/net/kemitix/thorp/console/ConsoleOut.scala
  console/src/main/scala/net/kemitix/thorp/console/MyConsole.scala
  console/src/main/scala/net/kemitix/thorp/console/package.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/SequencePlan.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyStorageService.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/SequencePlanTest.scala
  core/src/test/scala/net/kemitix/thorp/core/StorageQueueEventSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/StorageQueueEvent.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventLogger.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/AmazonS3.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Copier.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Deleter.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ListerLogger.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ClientException.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageServiceBuilder.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/CopierTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/S3StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderSuite.scala
Labels: enhancement

#118 Update aws-java-sdk-s3 to 1.11.596
  build.sbt
Labels: enhancement

#121 Remove Monocle dependency
  CHANGELOG.org
  build.sbt
  core/src/main/scala/net/kemitix/thorp/core/ConfigOptions.scala
  core/src/main/scala/net/kemitix/thorp/core/Counters.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Config.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteKey.scala
  domain/src/main/scala/net/kemitix/thorp/domain/SimpleLens.scala
  domain/src/test/scala/net/kemitix/thorp/domain/SimpleLensTest.scala
Labels: enhancement

#122 Ensure file handles are always closed
  CHANGELOG.org
  core/src/main/scala/net/kemitix/thorp/core/MD5HashGenerator.scala
Labels: enhancement

#124 Don't use String as key in Map for hashes
  CHANGELOG.org
  core/src/main/scala/net/kemitix/thorp/core/SimpleHashService.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyHashService.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/S3MetaDataEnricherSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/SequencePlanTest.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/HashType.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/HashService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ETag.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3HashService.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
Labels: enhancement

#133 Convert Storage to full ZIO effect module
  CHANGELOG.org
  cli/src/main/scala/net/kemitix/thorp/cli/CliArgs.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  cli/src/test/scala/net/kemitix/thorp/cli/CliArgsTest.scala
  cli/src/test/scala/net/kemitix/thorp/cli/ProgramTest.scala
  console/src/main/scala/net/kemitix/thorp/console/Console.scala
  console/src/main/scala/net/kemitix/thorp/console/MyConsole.scala
  console/src/main/scala/net/kemitix/thorp/console/package.scala
  core/src/main/scala/net/kemitix/thorp/core/CoreTypes.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyStorageService.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/SyncSuite.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/Storage.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/StorageService.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/AmazonS3.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/AmazonTransferManager.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/AmazonUpload.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Copier.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Deleter.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ListerLogger.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ClientException.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageService.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3StorageServiceBuilder.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/CopierTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/DeleterTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ListerTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/S3StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
Labels: refactoring

#134 Convert Config to full ZIO effect module
  CHANGELOG.org
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  config/src/main/scala/net/kemitix/thorp/config/CliArgs.scala
  config/src/main/scala/net/kemitix/thorp/config/Config.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigOption.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigOptions.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigQuery.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigValidation.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigValidationException.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigValidator.scala
  config/src/main/scala/net/kemitix/thorp/config/Configuration.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigurationBuilder.scala
  config/src/main/scala/net/kemitix/thorp/config/ParseConfigFile.scala
  config/src/main/scala/net/kemitix/thorp/config/ParseConfigLines.scala
  config/src/main/scala/net/kemitix/thorp/config/Resource.scala
  config/src/main/scala/net/kemitix/thorp/config/SourceConfigLoader.scala
  config/src/main/scala/net/kemitix/thorp/config/package.scala
  config/src/test/scala/net/kemitix/thorp/config/CliArgsTest.scala
  console/src/main/scala/net/kemitix/thorp/console/package.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/CoreTypes.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFiles.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/S3MetaDataEnricher.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigOptionTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigQueryTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigurationBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/KeyGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigFileTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigLinesTest.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/S3MetaDataEnricherSuite.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Config.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ETagGeneratorTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
Labels: refactoring

#135 Create FileSystem as full ZIO effect module
  CHANGELOG.org
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Main.scala
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigurationBuilder.scala
  config/src/main/scala/net/kemitix/thorp/config/ParseConfigFile.scala
  config/src/main/scala/net/kemitix/thorp/config/SourceConfigLoader.scala
  console/src/main/scala/net/kemitix/thorp/console/Console.scala
  console/src/main/scala/net/kemitix/thorp/console/package.scala
  core/src/main/scala/net/kemitix/thorp/core/CoreTypes.scala
  core/src/main/scala/net/kemitix/thorp/core/HashService.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/MD5HashGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/Remote.scala
  core/src/main/scala/net/kemitix/thorp/core/SimpleHashService.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigOptionTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ConfigurationBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyHashService.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/MD5HashGeneratorTest.scala
  core/src/test/scala/net/kemitix/thorp/core/ParseConfigFileTest.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteKey.scala
  filesystem/src/main/scala/net/kemitix/thorp/filesystem/FS.scala
  filesystem/src/main/scala/net/kemitix/thorp/filesystem/FileSystem.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/HashService.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/Storage.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ETagGenerator.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ListerLogger.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3HashService.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ETagGeneratorTest.scala
Labels: refactoring

#138 Merge config package object with Config object
  build.sbt
  cli/src/main/scala/net/kemitix/thorp/cli/Program.scala
  config/src/main/scala/net/kemitix/thorp/config/Config.scala
  config/src/main/scala/net/kemitix/thorp/config/package.scala
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncLogging.scala
  core/src/main/scala/net/kemitix/thorp/core/ThorpArchive.scala
  core/src/main/scala/net/kemitix/thorp/core/UnversionedMirrorArchive.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/DummyStorageService.scala
  core/src/test/scala/net/kemitix/thorp/core/LocalFileStreamSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  storage-api/src/main/scala/net/kemitix/thorp/storage/api/Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
Labels: refactoring

#139 Merge FS object into FileSystem object
  config/src/main/scala/net/kemitix/thorp/config/ParseConfigFile.scala
  core/src/main/scala/net/kemitix/thorp/core/MD5HashGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/Remote.scala
  filesystem/src/main/scala/net/kemitix/thorp/filesystem/FS.scala
  filesystem/src/main/scala/net/kemitix/thorp/filesystem/FileSystem.scala
Labels: refactoring
