Repository kemitix/thorp, pull requests merged in 2019-09, with the labels that each got.

#176 Upgrade to Scala 2.13.0
  .travis.yml
  build.sbt
  core/src/main/scala/net/kemitix/thorp/core/ActionGenerator.scala
  core/src/main/scala/net/kemitix/thorp/core/EventQueue.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFileStream.scala
  core/src/main/scala/net/kemitix/thorp/core/LocalFiles.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanBuilder.scala
  core/src/main/scala/net/kemitix/thorp/core/PlanExecutor.scala
  core/src/main/scala/net/kemitix/thorp/core/SyncPlan.scala
  core/src/test/scala/net/kemitix/thorp/core/ActionGeneratorSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/MatchedMetadataEnricherSuite.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanBuilderTest.scala
  core/src/test/scala/net/kemitix/thorp/core/PlanExecutorTest.scala
  domain/src/main/scala/net/kemitix/thorp/domain/HexEncoder.scala
  domain/src/main/scala/net/kemitix/thorp/domain/NonUnit.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteObjects.scala
  filesystem/src/main/scala/net/kemitix/thorp/filesystem/FileSystem.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ObjectsByHash.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3ObjectsByKey.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ListerTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/S3ObjectsByHashSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
Labels: enhancement

#180 Update sbt to 1.3.0
  project/build.properties
Labels: dependencies

#184 Code coverage
  project/plugins.sbt
Labels: enhancement

#186 Update sbt-ci-release to 1.3.1
  project/plugins.sbt
Labels: dependencies

#189 Enable Coverage reporting to Codecov
  .travis.yml
  project/plugins.sbt
Labels: enhancement

#190 Remove dead code
  app/src/main/scala/net/kemitix/thorp/Program.scala
  build.sbt
  config/src/test/scala/net/kemitix/thorp/config/ConfigQueryTest.scala
  config/src/test/scala/net/kemitix/thorp/config/ConfigurationBuilderTest.scala
  console/src/main/scala/net/kemitix/thorp/console/ConsoleOut.scala
  domain/src/main/scala/net/kemitix/thorp/domain/MatchedMetadata.scala
  domain/src/main/scala/net/kemitix/thorp/domain/Monoid.scala
  domain/src/main/scala/net/kemitix/thorp/domain/NonUnit.scala
  domain/src/main/scala/net/kemitix/thorp/domain/RemoteMetaData.scala
  domain/src/main/scala/net/kemitix/thorp/domain/StorageEvent.scala
  domain/src/main/scala/net/kemitix/thorp/domain/StorageQueueEvent.scala
  domain/src/main/scala/net/kemitix/thorp/domain/SyncTotals.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventListener.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadProgressEvent.scala
  domain/src/test/scala/net/kemitix/thorp/domain/TemporaryFolder.scala
  filesystem/src/test/scala/net/kemitix/thorp/filesystem/MD5HashGeneratorTest.scala
  lib/src/main/scala/net/kemitix/thorp/lib/ActionGenerator.scala
  lib/src/main/scala/net/kemitix/thorp/lib/CoreTypes.scala
  lib/src/main/scala/net/kemitix/thorp/lib/EventQueue.scala
  lib/src/main/scala/net/kemitix/thorp/lib/KeyGenerator.scala
  lib/src/main/scala/net/kemitix/thorp/lib/LocalFileStream.scala
  lib/src/main/scala/net/kemitix/thorp/lib/LocalFileSystem.scala
  lib/src/main/scala/net/kemitix/thorp/lib/LocalFileValidator.scala
  lib/src/main/scala/net/kemitix/thorp/lib/LocalFiles.scala
  lib/src/main/scala/net/kemitix/thorp/lib/PlanBuilder.scala
  lib/src/main/scala/net/kemitix/thorp/lib/PlanExecutor.scala
  lib/src/main/scala/net/kemitix/thorp/lib/Remote.scala
  lib/src/main/scala/net/kemitix/thorp/lib/S3MetaDataEnricher.scala
  lib/src/main/scala/net/kemitix/thorp/lib/SequencePlan.scala
  lib/src/main/scala/net/kemitix/thorp/lib/SyncLogging.scala
  lib/src/main/scala/net/kemitix/thorp/lib/SyncPlan.scala
  lib/src/main/scala/net/kemitix/thorp/lib/ThorpArchive.scala
  lib/src/main/scala/net/kemitix/thorp/lib/UnversionedMirrorArchive.scala
  lib/src/test/scala/net/kemitix/thorp/lib/ActionGeneratorSuite.scala
  lib/src/test/scala/net/kemitix/thorp/lib/DummyStorageService.scala
  lib/src/test/scala/net/kemitix/thorp/lib/EIPTest.scala
  lib/src/test/scala/net/kemitix/thorp/lib/KeyGeneratorSuite.scala
  lib/src/test/scala/net/kemitix/thorp/lib/LocalFileStreamSuite.scala
  lib/src/test/scala/net/kemitix/thorp/lib/MatchedMetadataEnricherSuite.scala
  lib/src/test/scala/net/kemitix/thorp/lib/PlanBuilderTest.scala
  lib/src/test/scala/net/kemitix/thorp/lib/PlanExecutorTest.scala
  lib/src/test/scala/net/kemitix/thorp/lib/SequencePlanTest.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Copier.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Deleter.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/CopierTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/DeleterTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ListerTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/StorageServiceSuite.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
  storage/src/main/scala/net/kemitix/thorp/storage/Storage.scala
Labels: refactoring

#192 Add more tests
  build.sbt
  domain/src/main/scala/net/kemitix/thorp/domain/Action.scala
  domain/src/main/scala/net/kemitix/thorp/domain/LocalFile.scala
  domain/src/test/scala/net/kemitix/thorp/domain/MD5HashData.scala
  lib/src/main/scala/net/kemitix/thorp/lib/LocalFileSystem.scala
  lib/src/test/scala/net/kemitix/thorp/lib/FileScannerTest.scala
  lib/src/test/scala/net/kemitix/thorp/lib/LocalFileSystemTest.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/hasher/ETagGenerator.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/hasher/ETagGeneratorTest.scala
Labels: enhancement

#196 Upload progress via uievent
  app/src/main/scala/net/kemitix/thorp/Program.scala
  build.sbt
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventListener.scala
  domain/src/main/scala/net/kemitix/thorp/domain/UploadEventLogger.scala
  lib/src/main/scala/net/kemitix/thorp/lib/LocalFileSystem.scala
  lib/src/main/scala/net/kemitix/thorp/lib/ThorpArchive.scala
  lib/src/main/scala/net/kemitix/thorp/lib/UnversionedMirrorArchive.scala
  lib/src/test/scala/net/kemitix/thorp/lib/LocalFileSystemTest.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
  storage/src/main/scala/net/kemitix/thorp/storage/Storage.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/ProgressEvent.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UIEvent.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UIShell.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UploadEventListener.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UploadProgressEvent.scala
Labels: enhancement

#200 Update sbt-ci-release to 1.3.2
  project/plugins.sbt
Labels: dependencies

#202 Update sbt-wartremover to 2.4.3
  project/plugins.sbt
Labels: dependencies

#204 Update sbt to 1.3.1
  project/build.properties
Labels: dependencies

#203 Update aws-java-sdk-s3 to 1.11.635
  build.sbt
Labels: dependencies

#209 Update zio, zio-streams to 1.0.0-RC13
  build.sbt
Labels: dependencies

#207 Update sbt to 1.3.2
  project/build.properties
Labels: dependencies

#206 Update jackson-databind to 2.9.10
  build.sbt
Labels: dependencies

#208 Update jackson-dataformat-cbor to 2.9.10
  build.sbt
Labels: dependencies

#162 Not wrapping exceptions thrown in waitForUploadResult
  app/src/main/scala/net/kemitix/thorp/Program.scala
  console/src/main/scala/net/kemitix/thorp/console/Console.scala
  console/src/main/scala/net/kemitix/thorp/console/ConsoleOut.scala
  lib/src/main/scala/net/kemitix/thorp/lib/LocalFileSystem.scala
  lib/src/main/scala/net/kemitix/thorp/lib/UnversionedMirrorArchive.scala
  lib/src/test/scala/net/kemitix/thorp/lib/LocalFileSystemTest.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/AmazonTransferManager.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/AmazonUpload.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Lister.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/ListerLogger.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/S3Storage.scala
  storage-aws/src/main/scala/net/kemitix/thorp/storage/aws/Uploader.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/AmazonS3ClientTestFixture.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/ListerTest.scala
  storage-aws/src/test/scala/net/kemitix/thorp/storage/aws/UploaderTest.scala
  storage/src/main/scala/net/kemitix/thorp/storage/Storage.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UIEvent.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UIShell.scala
Labels: bug

#211 Update sbt-ci-release to 1.4.31
  project/plugins.sbt
Labels: dependencies

#214 Update jackson-databind to 2.10.0
  build.sbt
Labels: dependencies

#188 Support multiple parallel uploads
  app/src/main/scala/net/kemitix/thorp/Program.scala
  cli/src/main/scala/net/kemitix/thorp/cli/CliArgs.scala
  cli/src/test/scala/net/kemitix/thorp/cli/CliArgsTest.scala
  config/src/main/scala/net/kemitix/thorp/config/Config.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigOption.scala
  config/src/main/scala/net/kemitix/thorp/config/ConfigOptions.scala
  config/src/main/scala/net/kemitix/thorp/config/Configuration.scala
  console/src/main/scala/net/kemitix/thorp/console/ConsoleOut.scala
  filesystem/src/main/scala/net/kemitix/thorp/filesystem/FileSystem.scala
  lib/src/main/scala/net/kemitix/thorp/lib/LocalFileSystem.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UIRequestCycle.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UIShell.scala
Labels: enhancement

#216 Update jackson-dataformat-cbor to 2.10.0
  build.sbt
Labels: dependencies

#217 Update aws-java-sdk-s3 to 1.11.641
  build.sbt
Labels: dependencies

#218 Progress UI should be updated when upload fails
  uishell/src/main/scala/net/kemitix/thorp/uishell/ProgressUI.scala
  uishell/src/main/scala/net/kemitix/thorp/uishell/UIShell.scala
Labels: bug

#221 Reduce Progress widget from 3 lines to 2
  uishell/src/main/scala/net/kemitix/thorp/uishell/ProgressUI.scala
Labels: enhancement
